spring.application.name=spring-apirest
server.port=8080

#Coneccion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/desafio?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
spring.datasource.username=desafio_practico
spring.datasource.password=4321

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#  JWT
jwt.secret=MiSecretoMuyLargoYSeguroQueCambiaEnProduccion12345

jwt.expirationMs=3600000



# OAuth2 GitHub
spring.security.oauth2.client.registration.github.client-id=Ov23lil8Kq4bZ6bETNlr
spring.security.oauth2.client.registration.github.client-secret=250ec858ac8b501188758d2fbe940314cd28b663
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}



logging.level.org.springframework.security=INFO
logging.level.sv.edu.udb=INFO


